name: CI

on: [push]

jobs:
  test:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [10.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node_version }} on ${{ matrix.os }}
      uses: actions/setup-node@v1
      with:
        version: ${{ matrix.node_version }}
    - name: yarn install and build
      run: |
        yarn install
        yarn run build
      env:
        CI: true
